[theme]
base                  = "dark"
primaryColor          = "#39D353"
backgroundColor       = "#0D0D0D"
secondaryBackgroundColor = "#0D1A0D"
textColor             = "#CCFFCC"
font                  = "monospace"
